name: Node CI

on:
  push:
    branchs:
    - site

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Display the GITHUB_TOKEN
      run: echo ${secrets.GITHUB_TOKEN}
      shell: bash
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy
      run: |
        npm install
        npm run build
        git config --global user.email "blandys@qq.com"
        git config --global user.name "lawrencebla"
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
