name: Node CI

on:
  pull_request:
    branchs:
    - site
  push:
    branchs:
    - site

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: deploy
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        mkdir .deploy
        cd .deploy

        git config --global user.email "gh_page@law4tina.com"
        git config --global user.name "github action"

        git clone --depth 1 --branch master --single-branch https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git .

        rm -rf ./* 
        cp -r ../public/* .
        
        git add -A .
        git commit -m 'Site updated'
        git branch -m master
        git push -q -u origin master
        
